project:
  type: website
  output-dir: docs

website:
  title: "Communicating with Data."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css
editor: visual

